services:
    mongomask:
        image: mongo:latest
        restart: "no"
        env_file:
            - .env
        volumes:
            - ../data:/data/db
            - ../dumps:/dump
            - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
