services:
    mongodb:
        image: mongo:latest
        restart: always
        ports:
            - "${MONGO_PORT}:27017"
        env_file:
            - .env
        volumes:
            - ./data:/data/db
            - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
